name: 'Tagger demo using GitHub actions'

on:
  push:
    tags:
      - '*CSB*'

jobs:
  tagger:
    runs-on: self-hosted
    name: Tagging script run
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Print hello world
        run: echo "Hello World"
      - name: Run the tagger script
        run: "python tagger.py ${{secrets.GRAPHQL_READ}}"
