name: 'Tagger demo using GitHub actions'

on:
  push:
    tags:
      - '*CSB*'

jobs:
  tagger:
    runs-on: self-hosted
    name: Tagging script run
    steps:
      - name: Run the tagger script
        run: "python tagger.py ${{secrets.GRAPHQL_READ}}"
